[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wordlesolver"
version = "0.1.0"
description = "Wordle assistant library based on Mathematics and Information Theory"
readme = "README.md"
authors = [
  { name="Fernando Mendi", email="fernandoomendi@gmail.com" },
]
license = "BSD-3-Clause"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas>=3",
    "tqdm>=4.69",
]

[project.optional-dependencies]
test = [
    "pytest>=9",
]

[project.scripts]
wordlesolver = "cli:main"

[project.urls]
repository = "https://github.com/fernandomendi/wordlesolver"

[tool.hatch.build.targets.wheel]
packages = ["core", "cli", "api"]

[tool.hatch.build.targets.wheel.sources]
"core/data" = "core/data"

[tool.pytest.ini_options]
testpaths = [
    "tests/",
]
