[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "wordlesolver"
version = "0.1.0"
description = "Wordle assistant library based on Mathematics and Information Theory"
readme = "README.md"
authors = [
  { name="Fernando Mendi", email="fernandoomendi@gmail.com" },
]
license = "BSD-3-Clause"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3",
    "click>=8",
    "flask>=3.1.3",
    "flask-cors>=6.0.5",
]

[project.optional-dependencies]
test = [
    "pytest>=9",
]

[project.scripts]
wordlesolver = "cli:main"

[project.urls]
repository = "https://github.com/fernandomendi/wordlesolver"

[tool.hatch.build.targets.wheel]
packages = ["core", "cli", "api"]

[tool.hatch.build.targets.wheel.sources]
"core/data" = "core/data"

[tool.pytest.ini_options]
testpaths = [
    "tests/",
]
markers = [
    "slow: marks tests as slow (skipped in CI)",
]
