name: Unit Tests

on: 
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run tests on updated code
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies (main + dev)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_dev.txt
        pip install -e .

    - name: Run unit tests
      run: |
        pytest tests/
